config/routes.rb
Kanban::Application.routes.draw do
  resources :tasks do
    member do
      put :change
      post :change
    end
    collection do
      get 'eisenhower'
      get 'deferred'
    end
  end

  get "pages/home"
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  def eisenhower_sort_index
    result=0
    if self.urgent=="true" then result-=4 end
    if self.important=="true" then result-=2 end
    if self.urgent==nil and self.important==nil then result=1 end
    return result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
require 'date'

class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  # GET /tasks
  # GET /tasks.json

  def all_undeferred_tasks
    return Task.all.where("deferred_until is null or deferred_until<=(?)",
								Date.today)
  end

  def tasks_eisen_pending_count
    tasks = Task.all
    eisen_pending = tasks.where("state='open' AND urgent is null and important is null")
    print "************* Eisen pending: ",eisen_pending.count
    return eisen_pending.count
  end
  helper_method :tasks_eisen_pending_count
  
  def index
    @tasks = all_undeferred_tasks()
    @open = @tasks.where(state:"open").sort_by &:eisenhower_sort_index
    @wip = @tasks.where(state:"wip").sort_by &:eisenhower_sort_index
    @closed = @tasks.where(state:"closed").sort_by &:eisenhower_sort_index
  end
  
  def eisenhower
    @tasks = Task.all
    @eisen_q1 = @tasks.where("state='open' AND urgent='true' AND important='true'")
    @eisen_q2 = @tasks.where("state='open' AND urgent='false' AND important='true'")
    @eisen_q3 = @tasks.where("state='open' AND urgent='true' AND important='false'")
    @eisen_q4 = @tasks.where("state='open' AND urgent='false' AND important='false'")
    @eisen_pending = @tasks.where("state='open' AND urgent is null and important is null")
  end

  def deferred
    @tasks = Task.all
    @deferred = @tasks.where("state!='closed' AND deferred_until > '#{Date.today}'")
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  def change
    [:state,:urgent,:important].each do |p|
      if params[p] then
        #Equivalent to the original
        #@task.update_attributes(state: params[:state].downcase())
        #Because (state: x) is the same as ("state"=>x)
        #And "state".to_sym() results in :state
        @task.update_attributes(p=>params[p.to_sym()].downcase())
      end
    end
    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "Task updated"}
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content,:state,:deferred_until)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <ul id="nav-mobile" class="left">
      <li><a href="/tasks">Kanban Board</a></li>
      <li><a href="/tasks/eisenhower">
		<%= if tasks_eisen_pending_count()>0 then "*" else "" end %>
		Eisenhower</a></li>
      <li><a href="/tasks/deferred">Deferred</a></li>
    </ul>
    <ul id="nav-mobile" class="right">
      <li>
        <%= link_to "Add task".html_safe,
            new_task_path, class: "btn" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kanban</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Hello world!</h1>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :autofocus=>true %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit class: "btn green" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="card-panel
      <%=
        if task.urgent=='true' and task.important=='true'
          then 'red'
        elsif task.urgent=='true' and task.important=='false'
          then 'orange'
        elsif task.urgent=='false' and task.important=='true'
          then 'green'
        else 'blue-grey' end%>
      darken-1" draggable="true"
    ondragstart="drag(event)" id="<%= dom_id(task) %>"
    ondrop="" ondragover="" style="padding:5px">
  <% if task.state=="open" %>
  <input type="checkbox" id="checkbox<%= dom_id(task) %>" class="filled-in"/>
  <label for="checkbox<%= dom_id(task) %>">
  <% end %>
  <div class="card-content white-text">
    <%= best_in_place task, :content, :as => :textarea %>
    <br/>
 </div>
  <% if task.state=="open" %>
  </label>
  <% end %>
  <div class="card-action" style="min-height: 16px">
    <%= best_in_place task, :deferred_until, :as => :date, :id => "deferdate",
	:place_holder => "<i class='fa fa-forward'></i>",
	:class=>"white-text"
    %>
    <%= link_to "<i class='fa fa-trash-o white-text' aria-hidden='true'></i>".html_safe,
            task_path(task), method: :delete,
            data: { confirm: 'Are you sure?' }, class: "right" %>
  </div>
</div>

app/views/tasks/deferred.html.erb
<div class="container">
  <div class="row">
    <% [["Deferred",@deferred]].each do |title,list| %>
      <div class="col l4 s4 grey" id="Col_<%= title %>"
          style="min-height: 80vh; border:1px solid white"
          ondrop="drop_status(event)" ondragover="allowDrop(event)">
        <h5><%= title %></h5>
        <%= render list %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Editing task</h1>

  <%= render 'form' %>

  <br />
  <%= link_to 'Back', tasks_path, class: "btn red" %>
</div>

app/views/tasks/eisenhower.html.erb
<div class="container">
  <div class="row">
    <div class="col l10 s10">
      <div class="row">
        <div class="col l6 s6 red" id="Quad_EisenQ1_true_true"
              style="border:1px solid white"
              ondrop="drop_eisenhower(event)" ondragover="allowDrop(event)">
            <h5 id="Quad_EisenQ1_true_true">Important and Urgent</h5>
            <%= render @eisen_q1 %>
        </div>
        <div class="col l6 s6 green" id="Quad_EisenQ2_false_true"
              style="border:1px solid white"
              ondrop="drop_eisenhower(event)" ondragover="allowDrop(event)">
            <h5 id="Quad_EisenQ2_false_true">Important not Urgent</h5>
            <%= render @eisen_q2 %>
        </div>
      </div>
      <div class="row">
        <div class="col l6 s6 yellow" id="Quad_EisenQ3_true_false"
              style="border:1px solid white"
              ondrop="drop_eisenhower(event)" ondragover="allowDrop(event)">
            <h5 id="Quad_EisenQ3_true_false">Urgent not Important</h5>
            <%= render @eisen_q3 %>
        </div>
        <div class="col l6 s6 grey" id="Quad_EisenQ4_false_false"
              style="border:1px solid white"
              ondrop="drop_eisenhower(event)" ondragover="allowDrop(event)">
            <h5 id="Quad_EisenQ4_false_false">Not Important or Urgent</h5>
            <%= render @eisen_q4 %>
        </div>
      </div>
    </div>
    <div class="col l2 s2 blue" id="Quad_EisenPending_null_null"
              style="border:1px solid white"
              ondrop="drop_eisenhower(event)" ondragover="allowDrop(event)">
      <h5>Pending</h5>
      <%= render @eisen_pending %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <% [["Open",@open],["WIP",@wip],["Closed",@closed]].each do |title,list| %>
      <div class="col l4 s4 grey" id="Col_<%= title %>"
          style="min-height: 80vh; border:1px solid white"
          ondrop="drop_status(event)" ondragover="allowDrop(event)">
        <h5><%= title %></h5>
        <%= render list %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New task</h1>

  <%= render 'form' %>
  <br />
  <%= link_to 'Back', tasks_path, class: "btn red" %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>